# Generated by Django 5.2.17 on 2026-10-01 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='قد بر حسب سانتی\u200cمتر', null=True, verbose_name='قد')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='وزن بر حسب کیلوگرم', max_digits=5, null=True, verbose_name='وزن')),
                ('referral_source', models.CharField(blank=True, choices=[('INSTAGRAM', 'اینستاگرام'), ('GOOGLE', 'گوگل'), ('FRIEND', 'معرفی دوستان'), ('TELEGRAM', 'تلگرام'), ('OTHER', 'سایر')], max_length=20, verbose_name='نحوه آشنایی با مربی')),
                ('referral_description', models.CharField(blank=True, max_length=255, verbose_name='توضیح نحوه آشنایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل شاگرد',
                'verbose_name_plural': 'پروفایل شاگردان',
            },
        ),
    ]
