# Generated by Django 5.2.17 on 2026-10-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه عضلانی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'گروه عضلانی',
                'verbose_name_plural': 'گروه\u200cهای عضلانی',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='نام حرکت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات حرکت')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'مبتدی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], default='BEGINNER', max_length=20, verbose_name='سطح حرکت')),
                ('is_system', models.BooleanField(default=False, verbose_name='حرکت سیستمی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_exercises', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='exercises.musclegroup', verbose_name='عضله اصلی')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup', verbose_name='عضلات فرعی')),
            ],
            options={
                'verbose_name': 'حرکت',
                'verbose_name_plural': 'حرکات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'عکس'), ('VIDEO', 'ویدئو'), ('GIF', 'گیف')], max_length=10, verbose_name='نوع رسانه')),
                ('file', models.FileField(upload_to='exercises/media/', verbose_name='فایل')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercises/thumbnails/', verbose_name='تصویر پیش\u200cنمایش')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رسانه اصلی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='exercises.exercise', verbose_name='حرکت')),
            ],
            options={
                'verbose_name': 'رسانه حرکت',
                'verbose_name_plural': 'رسانه\u200cهای حرکات',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_system', 'is_active'], name='exercise_system_active_idx'),
        ),
    ]
