# Generated by Django 5.2.17 on 2026-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='common_mistake',
            field=models.TextField(blank=True, verbose_name='اشتباه رایج'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=150, verbose_name='تجهیزات موردنیاز'),
        ),
    ]
