# Generated by Django 5.2.17 on 2026-10-07 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('BODYBUILDING', 'بدنسازی'), ('NUTRITION', 'تغذیه'), ('CORRECTIVE', 'اصلاحی')], max_length=20, verbose_name='نوع برنامه')),
                ('status', models.CharField(choices=[('WAITING', 'در انتظار'), ('PREPARING', 'در حال آماده\u200cسازی'), ('ACTIVE', 'فعال'), ('EXPIRED', 'منقضی شده')], default='WAITING', max_length=20, verbose_name='وضعیت')),
                ('duration_days', models.PositiveSmallIntegerField(default=45, verbose_name='مدت برنامه به روز')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='students.studentprofile', verbose_name='شاگرد')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'status'], name='program_student_status_idx'), models.Index(fields=['program_type', 'status'], name='program_type_status_idx')],
            },
        ),
    ]
