# Generated by Django 5.2.17 on 2026-10-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_common_mistake_exercise_equipment'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان جلسه')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات جلسه')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.program', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'جلسه برنامه',
                'verbose_name_plural': 'جلسات برنامه',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='تعداد ست')),
                ('reps', models.CharField(max_length=50, verbose_name='تکرار')),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='استراحت بین ست\u200cها به ثانیه')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='وزنه یا شدت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات مربی')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب حرکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_exercises', to='exercises.exercise', verbose_name='حرکت')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programday', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'حرکت برنامه',
                'verbose_name_plural': 'حرکات برنامه',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='programday',
            index=models.Index(fields=['program', 'order'], name='program_day_order_idx'),
        ),
        migrations.AddIndex(
            model_name='programexercise',
            index=models.Index(fields=['program_day', 'order'], name='program_exercise_order_idx'),
        ),
    ]
