# Generated by Django 5.2.17 on 2026-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programexercise_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='programday',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف شده'),
        ),
    ]
