# Generated by Django 5.2.17 on 2026-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_programday_deleted_at_programday_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف شده'),
        ),
    ]
