# Generated by Django 5.2.17 on 2026-10-10 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_deleted_at_program_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان روز یا الگو')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('program', models.ForeignKey(limit_choices_to={'program_type': 'NUTRITION'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_days', to='programs.program', verbose_name='برنامه تغذیه')),
            ],
            options={
                'verbose_name': 'روز برنامه تغذیه',
                'verbose_name_plural': 'روزهای برنامه تغذیه',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['program', 'order'], name='nutrition_day_order_idx')],
            },
        ),
    ]
