# Generated by Django 5.2.17 on 2026-10-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_nutritionday'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان وعده')),
                ('meal_time', models.TimeField(blank=True, null=True, verbose_name='زمان وعده')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات مربی')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('nutrition_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='programs.nutritionday', verbose_name='روز تغذیه')),
            ],
            options={
                'verbose_name': 'وعده غذایی',
                'verbose_name_plural': 'وعده\u200cهای غذایی',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['nutrition_day', 'order'], name='nutrition_meal_order_idx')],
            },
        ),
    ]
