# Generated by Django 5.2.17 on 2026-10-10 06:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_nutritionmeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام ماده غذایی')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مقدار مصرف')),
                ('unit', models.CharField(choices=[('GRAM', 'گرم'), ('MILLILITER', 'میلی\u200cلیتر'), ('PIECE', 'عدد'), ('CUP', 'لیوان'), ('TABLESPOON', 'قاشق غذاخوری'), ('TEASPOON', 'قاشق چای\u200cخوری'), ('SLICE', 'برش'), ('PALM', 'کف دست'), ('BOWL', 'کاسه')], max_length=20, verbose_name='واحد اندازه\u200cگیری')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات مربی')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('nutrition_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='programs.nutritionmeal', verbose_name='وعده غذایی')),
            ],
            options={
                'verbose_name': 'ماده غذایی برنامه',
                'verbose_name_plural': 'مواد غذایی برنامه',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['nutrition_meal', 'order'], name='nutrition_food_order_idx')],
            },
        ),
    ]
